name: yumemi_code_check
description: A new Flutter project.
version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Uitilty
  quiver: ^3.1.0

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  cupertino_icons: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  #Pub.devのパッケージがうまく動かないのでGitHubから得る 
  flutter_launcher_icons:
    git:
      url: https://github.com/Davenchy/flutter_launcher_icons.git
      ref: fixMinSdkParseFlutter2.8

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

flutter_icons:
  android: true
  ios: true
