name: yumemi_code_check
description: A new Flutter project.
version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

flutter_icons:
  android: true
  ios: true
